<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Workshop 4 Data Visualisation | Advanced Data Skills, Open Science and Reproducibility 2024/25</title>
  <meta name="description" content="Workshop 4 Data Visualisation | Advanced Data Skills, Open Science and Reproducibility 2024/25" />
  <meta name="generator" content="bookdown 0.36 and GitBook 2.6.7" />

  <meta property="og:title" content="Workshop 4 Data Visualisation | Advanced Data Skills, Open Science and Reproducibility 2024/25" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Workshop 4 Data Visualisation | Advanced Data Skills, Open Science and Reproducibility 2024/25" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="data-wrangling-and-data-summarising.html"/>
<link rel="next" href="r-markdown.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">PCHN63101</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a></li>
<li class="chapter" data-level="1" data-path="open-science.html"><a href="open-science.html"><i class="fa fa-check"></i><b>1</b> Open Science</a>
<ul>
<li class="chapter" data-level="1.1" data-path="open-science.html"><a href="open-science.html#open-research-and-reproducibility"><i class="fa fa-check"></i><b>1.1</b> Open Research and Reproducibility</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="open-science.html"><a href="open-science.html#how-to-do-reproducible-research"><i class="fa fa-check"></i><b>1.1.1</b> How to do Reproducible Research</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="open-science.html"><a href="open-science.html#experimental-power"><i class="fa fa-check"></i><b>1.2</b> Experimental Power</a></li>
<li class="chapter" data-level="1.3" data-path="open-science.html"><a href="open-science.html#open-source-software"><i class="fa fa-check"></i><b>1.3</b> Open Source Software</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="open-science.html"><a href="open-science.html#statistical-and-scientific-computing"><i class="fa fa-check"></i><b>1.3.1</b> Statistical and Scientific Computing</a></li>
<li class="chapter" data-level="1.3.2" data-path="open-science.html"><a href="open-science.html#document-creation"><i class="fa fa-check"></i><b>1.3.2</b> Document Creation</a></li>
<li class="chapter" data-level="1.3.3" data-path="open-science.html"><a href="open-science.html#building-experiments"><i class="fa fa-check"></i><b>1.3.3</b> Building Experiments</a></li>
<li class="chapter" data-level="1.3.4" data-path="open-science.html"><a href="open-science.html#linux"><i class="fa fa-check"></i><b>1.3.4</b> Linux</a></li>
<li class="chapter" data-level="1.3.5" data-path="open-science.html"><a href="open-science.html#more-reading"><i class="fa fa-check"></i><b>1.3.5</b> More Reading</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html"><i class="fa fa-check"></i><b>2</b> R and RStudio</a>
<ul>
<li class="chapter" data-level="2.1" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#why-r"><i class="fa fa-check"></i><b>2.1</b> Why R?</a></li>
<li class="chapter" data-level="2.2" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#getting-started"><i class="fa fa-check"></i><b>2.2</b> Getting Started</a></li>
<li class="chapter" data-level="2.3" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#keeping-things-organised"><i class="fa fa-check"></i><b>2.3</b> Keeping Things Organised</a></li>
<li class="chapter" data-level="2.4" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#good-coding-style"><i class="fa fa-check"></i><b>2.4</b> Good Coding Style</a></li>
<li class="chapter" data-level="2.5" data-path="r-and-rstudio.html"><a href="r-and-rstudio.html#your-first-r-script"><i class="fa fa-check"></i><b>2.5</b> Your First R Script</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html"><i class="fa fa-check"></i><b>3</b> Data Wrangling and Data Summarising</a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#wrangling-your-data"><i class="fa fa-check"></i><b>3.1</b> Wrangling your data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#loading-the-tidyverse"><i class="fa fa-check"></i><b>3.1.1</b> Loading the Tidyverse</a></li>
<li class="chapter" data-level="3.1.2" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#using-head-and-str"><i class="fa fa-check"></i><b>3.1.2</b> Using <code>head()</code> and <code>str()</code></a></li>
<li class="chapter" data-level="3.1.3" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#use-select-to-select-columns"><i class="fa fa-check"></i><b>3.1.3</b> Use <code>select()</code> to select columns</a></li>
<li class="chapter" data-level="3.1.4" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#use-filter-to-select-rows"><i class="fa fa-check"></i><b>3.1.4</b> Use <code>filter()</code> to select rows</a></li>
<li class="chapter" data-level="3.1.5" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#the-pipe"><i class="fa fa-check"></i><b>3.1.5</b> The pipe <code>%&gt;%</code></a></li>
<li class="chapter" data-level="3.1.6" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#tidying-up-a-dataset"><i class="fa fa-check"></i><b>3.1.6</b> Tidying up a dataset</a></li>
<li class="chapter" data-level="3.1.7" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#joining-two-datasets"><i class="fa fa-check"></i><b>3.1.7</b> Joining Two Datasets</a></li>
<li class="chapter" data-level="3.1.8" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#your-challenge-complete-this-before-the-in-person-session"><i class="fa fa-check"></i><b>3.1.8</b> Your challenge (complete this before the in-person session)</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#summarising-your-data"><i class="fa fa-check"></i><b>3.2</b> Summarising your data</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#using-group_by-and-summarise"><i class="fa fa-check"></i><b>3.2.1</b> Using <code>group_by()</code> and <code>summarise()</code></a></li>
<li class="chapter" data-level="3.2.2" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#adding-columns-using-mutate"><i class="fa fa-check"></i><b>3.2.2</b> Adding columns using <code>mutate()</code></a></li>
<li class="chapter" data-level="3.2.3" data-path="data-wrangling-and-data-summarising.html"><a href="data-wrangling-and-data-summarising.html#your-challenge-do-this-during-the-in-person-session"><i class="fa fa-check"></i><b>3.2.3</b> Your challenge (do this during the in-person session)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-visualisation.html"><a href="data-visualisation.html"><i class="fa fa-check"></i><b>4</b> Data Visualisation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="data-visualisation.html"><a href="data-visualisation.html#the-basics-of-ggplot2"><i class="fa fa-check"></i><b>4.1</b> The Basics of ggplot2</a></li>
<li class="chapter" data-level="4.2" data-path="data-visualisation.html"><a href="data-visualisation.html#your-first-visualisation"><i class="fa fa-check"></i><b>4.2</b> Your First Visualisation</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="data-visualisation.html"><a href="data-visualisation.html#improving-the-plot"><i class="fa fa-check"></i><b>4.2.1</b> Improving the Plot</a></li>
<li class="chapter" data-level="4.2.2" data-path="data-visualisation.html"><a href="data-visualisation.html#adding-summary-statistics"><i class="fa fa-check"></i><b>4.2.2</b> Adding Summary Statistics</a></li>
<li class="chapter" data-level="4.2.3" data-path="data-visualisation.html"><a href="data-visualisation.html#the-finished-plot"><i class="fa fa-check"></i><b>4.2.3</b> The Finished(?) Plot</a></li>
<li class="chapter" data-level="4.2.4" data-path="data-visualisation.html"><a href="data-visualisation.html#using-facet_wrap"><i class="fa fa-check"></i><b>4.2.4</b> Using <code>facet_wrap()</code></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="data-visualisation.html"><a href="data-visualisation.html#scatterplots"><i class="fa fa-check"></i><b>4.3</b> Scatterplots</a></li>
<li class="chapter" data-level="4.4" data-path="data-visualisation.html"><a href="data-visualisation.html#plotting-histograms"><i class="fa fa-check"></i><b>4.4</b> Plotting Histograms</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="data-visualisation.html"><a href="data-visualisation.html#the-ggridges-package"><i class="fa fa-check"></i><b>4.4.1</b> The <code>ggridges</code> Package</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="data-visualisation.html"><a href="data-visualisation.html#the-nhanes-dataset"><i class="fa fa-check"></i><b>4.5</b> The NHANES Dataset</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="data-visualisation.html"><a href="data-visualisation.html#tidying-the-data"><i class="fa fa-check"></i><b>4.5.1</b> Tidying the Data</a></li>
<li class="chapter" data-level="4.5.2" data-path="data-visualisation.html"><a href="data-visualisation.html#plotting-a-histogram"><i class="fa fa-check"></i><b>4.5.2</b> Plotting a Histogram</a></li>
<li class="chapter" data-level="4.5.3" data-path="data-visualisation.html"><a href="data-visualisation.html#summary-statistics"><i class="fa fa-check"></i><b>4.5.3</b> Summary Statistics</a></li>
<li class="chapter" data-level="4.5.4" data-path="data-visualisation.html"><a href="data-visualisation.html#geom_violin"><i class="fa fa-check"></i><b>4.5.4</b> <code>geom_violin()</code></a></li>
<li class="chapter" data-level="4.5.5" data-path="data-visualisation.html"><a href="data-visualisation.html#plotting-interaction-effects"><i class="fa fa-check"></i><b>4.5.5</b> Plotting Interaction Effects</a></li>
<li class="chapter" data-level="4.5.6" data-path="data-visualisation.html"><a href="data-visualisation.html#histograms-with-facet_wrap"><i class="fa fa-check"></i><b>4.5.6</b> Histograms with <code>facet_wrap()</code></a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="data-visualisation.html"><a href="data-visualisation.html#your-challenge-do-this-during-the-in-person-session-1"><i class="fa fa-check"></i><b>4.6</b> Your Challenge (do this during the in-person session)</a></li>
<li class="chapter" data-level="4.7" data-path="data-visualisation.html"><a href="data-visualisation.html#additional-resources"><i class="fa fa-check"></i><b>4.7</b> Additional Resources</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="r-markdown.html"><a href="r-markdown.html"><i class="fa fa-check"></i><b>5</b> R Markdown</a>
<ul>
<li class="chapter" data-level="5.1" data-path="r-markdown.html"><a href="r-markdown.html#overview"><i class="fa fa-check"></i><b>5.1</b> Overview</a></li>
<li class="chapter" data-level="5.2" data-path="r-markdown.html"><a href="r-markdown.html#your-challenge-do-this-during-the-in-person-session-2"><i class="fa fa-check"></i><b>5.2</b> Your Challenge (do this during the in-person session)</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="regression-part-1.html"><a href="regression-part-1.html"><i class="fa fa-check"></i><b>6</b> Regression Part 1</a>
<ul>
<li class="chapter" data-level="6.1" data-path="regression-part-1.html"><a href="regression-part-1.html#overview-1"><i class="fa fa-check"></i><b>6.1</b> Overview</a></li>
<li class="chapter" data-level="6.2" data-path="regression-part-1.html"><a href="regression-part-1.html#simple-linear-regression"><i class="fa fa-check"></i><b>6.2</b> Simple Linear Regression</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="regression-part-1.html"><a href="regression-part-1.html#the-packages-we-need"><i class="fa fa-check"></i><b>6.2.1</b> The Packages We Need</a></li>
<li class="chapter" data-level="6.2.2" data-path="regression-part-1.html"><a href="regression-part-1.html#import-the-data"><i class="fa fa-check"></i><b>6.2.2</b> Import the Data</a></li>
<li class="chapter" data-level="6.2.3" data-path="regression-part-1.html"><a href="regression-part-1.html#tidy-the-data"><i class="fa fa-check"></i><b>6.2.3</b> Tidy the Data</a></li>
<li class="chapter" data-level="6.2.4" data-path="regression-part-1.html"><a href="regression-part-1.html#plot-the-data"><i class="fa fa-check"></i><b>6.2.4</b> Plot the Data</a></li>
<li class="chapter" data-level="6.2.5" data-path="regression-part-1.html"><a href="regression-part-1.html#pearsons-r"><i class="fa fa-check"></i><b>6.2.5</b> Pearson’s r</a></li>
<li class="chapter" data-level="6.2.6" data-path="regression-part-1.html"><a href="regression-part-1.html#model-the-data"><i class="fa fa-check"></i><b>6.2.6</b> Model the Data</a></li>
<li class="chapter" data-level="6.2.7" data-path="regression-part-1.html"><a href="regression-part-1.html#checking-our-assumptions"><i class="fa fa-check"></i><b>6.2.7</b> Checking Our Assumptions</a></li>
<li class="chapter" data-level="6.2.8" data-path="regression-part-1.html"><a href="regression-part-1.html#interpreting-our-model"><i class="fa fa-check"></i><b>6.2.8</b> Interpreting Our Model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="regression-part-2.html"><a href="regression-part-2.html"><i class="fa fa-check"></i><b>7</b> Regression Part 2</a>
<ul>
<li class="chapter" data-level="7.1" data-path="regression-part-2.html"><a href="regression-part-2.html#overview-2"><i class="fa fa-check"></i><b>7.1</b> Overview</a></li>
<li class="chapter" data-level="7.2" data-path="regression-part-2.html"><a href="regression-part-2.html#multiple-regression"><i class="fa fa-check"></i><b>7.2</b> Multiple Regression</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="regression-part-2.html"><a href="regression-part-2.html#the-packages-we-need-1"><i class="fa fa-check"></i><b>7.2.1</b> The Packages We Need</a></li>
<li class="chapter" data-level="7.2.2" data-path="regression-part-2.html"><a href="regression-part-2.html#import-the-data-1"><i class="fa fa-check"></i><b>7.2.2</b> Import the Data</a></li>
<li class="chapter" data-level="7.2.3" data-path="regression-part-2.html"><a href="regression-part-2.html#model-the-data-1"><i class="fa fa-check"></i><b>7.2.3</b> Model the Data</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="regression-part-2.html"><a href="regression-part-2.html#stepwise-regression"><i class="fa fa-check"></i><b>7.3</b> Stepwise regression</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="regression-part-2.html"><a href="regression-part-2.html#model-the-data-2"><i class="fa fa-check"></i><b>7.3.1</b> Model the Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="anova-part-1.html"><a href="anova-part-1.html"><i class="fa fa-check"></i><b>8</b> ANOVA Part 1</a>
<ul>
<li class="chapter" data-level="8.1" data-path="anova-part-1.html"><a href="anova-part-1.html#overview-3"><i class="fa fa-check"></i><b>8.1</b> Overview</a></li>
<li class="chapter" data-level="8.2" data-path="anova-part-1.html"><a href="anova-part-1.html#between-participants-anova"><i class="fa fa-check"></i><b>8.2</b> Between Participants ANOVA</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="anova-part-1.html"><a href="anova-part-1.html#loading-our-packages"><i class="fa fa-check"></i><b>8.2.1</b> Loading our Packages</a></li>
<li class="chapter" data-level="8.2.2" data-path="anova-part-1.html"><a href="anova-part-1.html#reading-in-our-data"><i class="fa fa-check"></i><b>8.2.2</b> Reading in our Data</a></li>
<li class="chapter" data-level="8.2.3" data-path="anova-part-1.html"><a href="anova-part-1.html#summarising-our-data"><i class="fa fa-check"></i><b>8.2.3</b> Summarising our Data</a></li>
<li class="chapter" data-level="8.2.4" data-path="anova-part-1.html"><a href="anova-part-1.html#visualising-our-data"><i class="fa fa-check"></i><b>8.2.4</b> Visualising our Data</a></li>
<li class="chapter" data-level="8.2.5" data-path="anova-part-1.html"><a href="anova-part-1.html#building-our-anova-model"><i class="fa fa-check"></i><b>8.2.5</b> Building our ANOVA Model</a></li>
<li class="chapter" data-level="8.2.6" data-path="anova-part-1.html"><a href="anova-part-1.html#interpreting-the-model-output"><i class="fa fa-check"></i><b>8.2.6</b> Interpreting the Model Output</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="anova-part-1.html"><a href="anova-part-1.html#repeated-measures-anova"><i class="fa fa-check"></i><b>8.3</b> Repeated Measures ANOVA</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="anova-part-1.html"><a href="anova-part-1.html#reading-in-our-data-1"><i class="fa fa-check"></i><b>8.3.1</b> Reading in our Data</a></li>
<li class="chapter" data-level="8.3.2" data-path="anova-part-1.html"><a href="anova-part-1.html#summarising-our-data-1"><i class="fa fa-check"></i><b>8.3.2</b> Summarising our Data</a></li>
<li class="chapter" data-level="8.3.3" data-path="anova-part-1.html"><a href="anova-part-1.html#visualising-our-data-1"><i class="fa fa-check"></i><b>8.3.3</b> Visualising our Data</a></li>
<li class="chapter" data-level="8.3.4" data-path="anova-part-1.html"><a href="anova-part-1.html#building-our-anova-model-1"><i class="fa fa-check"></i><b>8.3.4</b> Building our ANOVA Model</a></li>
<li class="chapter" data-level="8.3.5" data-path="anova-part-1.html"><a href="anova-part-1.html#interpreting-the-model-output-1"><i class="fa fa-check"></i><b>8.3.5</b> Interpreting the Model Output</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="anova-part-1.html"><a href="anova-part-1.html#factorial-anova"><i class="fa fa-check"></i><b>8.4</b> Factorial ANOVA</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="anova-part-1.html"><a href="anova-part-1.html#reading-in-our-data-2"><i class="fa fa-check"></i><b>8.4.1</b> Reading in our Data</a></li>
<li class="chapter" data-level="8.4.2" data-path="anova-part-1.html"><a href="anova-part-1.html#summarising-our-data-2"><i class="fa fa-check"></i><b>8.4.2</b> Summarising our Data</a></li>
<li class="chapter" data-level="8.4.3" data-path="anova-part-1.html"><a href="anova-part-1.html#visualising-our-data-2"><i class="fa fa-check"></i><b>8.4.3</b> Visualising our Data</a></li>
<li class="chapter" data-level="8.4.4" data-path="anova-part-1.html"><a href="anova-part-1.html#building-our-anova-model-2"><i class="fa fa-check"></i><b>8.4.4</b> Building our ANOVA Model</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="anova-part-1.html"><a href="anova-part-1.html#your-challenge-do-this-during-the-in-person-session-3"><i class="fa fa-check"></i><b>8.5</b> Your Challenge (do this during the in-person session)</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="anova-part-1.html"><a href="anova-part-1.html#question-1"><i class="fa fa-check"></i><b>8.5.1</b> Question 1</a></li>
<li class="chapter" data-level="8.5.2" data-path="anova-part-1.html"><a href="anova-part-1.html#question-2"><i class="fa fa-check"></i><b>8.5.2</b> Question 2</a></li>
<li class="chapter" data-level="8.5.3" data-path="anova-part-1.html"><a href="anova-part-1.html#question-3"><i class="fa fa-check"></i><b>8.5.3</b> Question 3</a></li>
<li class="chapter" data-level="8.5.4" data-path="anova-part-1.html"><a href="anova-part-1.html#question-4"><i class="fa fa-check"></i><b>8.5.4</b> Question 4</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="anova-part-1.html"><a href="anova-part-1.html#answers"><i class="fa fa-check"></i><b>8.6</b> Answers</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="anova-part-1.html"><a href="anova-part-1.html#question-1-1"><i class="fa fa-check"></i><b>8.6.1</b> Question 1</a></li>
<li class="chapter" data-level="8.6.2" data-path="anova-part-1.html"><a href="anova-part-1.html#question-2-1"><i class="fa fa-check"></i><b>8.6.2</b> Question 2</a></li>
<li class="chapter" data-level="8.6.3" data-path="anova-part-1.html"><a href="anova-part-1.html#question-3-1"><i class="fa fa-check"></i><b>8.6.3</b> Question 3</a></li>
<li class="chapter" data-level="8.6.4" data-path="anova-part-1.html"><a href="anova-part-1.html#question-4-1"><i class="fa fa-check"></i><b>8.6.4</b> Question 4</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="anova-part-2.html"><a href="anova-part-2.html"><i class="fa fa-check"></i><b>9</b> ANOVA Part 2</a>
<ul>
<li class="chapter" data-level="9.1" data-path="anova-part-2.html"><a href="anova-part-2.html#overview-4"><i class="fa fa-check"></i><b>9.1</b> Overview</a></li>
<li class="chapter" data-level="9.2" data-path="anova-part-2.html"><a href="anova-part-2.html#building-our-ancova"><i class="fa fa-check"></i><b>9.2</b> Building our ANCOVA</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="anova-part-2.html"><a href="anova-part-2.html#loading-our-packages-1"><i class="fa fa-check"></i><b>9.2.1</b> Loading our Packages</a></li>
<li class="chapter" data-level="9.2.2" data-path="anova-part-2.html"><a href="anova-part-2.html#reading-in-our-data-3"><i class="fa fa-check"></i><b>9.2.2</b> Reading in our Data</a></li>
<li class="chapter" data-level="9.2.3" data-path="anova-part-2.html"><a href="anova-part-2.html#summarising-our-data-3"><i class="fa fa-check"></i><b>9.2.3</b> Summarising our Data</a></li>
<li class="chapter" data-level="9.2.4" data-path="anova-part-2.html"><a href="anova-part-2.html#visualising-our-data-3"><i class="fa fa-check"></i><b>9.2.4</b> Visualising our Data</a></li>
<li class="chapter" data-level="9.2.5" data-path="anova-part-2.html"><a href="anova-part-2.html#building-our-anova-model-3"><i class="fa fa-check"></i><b>9.2.5</b> Building our ANOVA model</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="anova-part-2.html"><a href="anova-part-2.html#ancova-as-a-special-case-of-regression"><i class="fa fa-check"></i><b>9.3</b> AN(C)OVA as a Special Case of Regression</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="anova-part-2.html"><a href="anova-part-2.html#visualising-our-data-4"><i class="fa fa-check"></i><b>9.3.1</b> Visualising our Data</a></li>
<li class="chapter" data-level="9.3.2" data-path="anova-part-2.html"><a href="anova-part-2.html#setting-up-our-contrasts"><i class="fa fa-check"></i><b>9.3.2</b> Setting up our Contrasts</a></li>
<li class="chapter" data-level="9.3.3" data-path="anova-part-2.html"><a href="anova-part-2.html#anova-as-a-linear-model"><i class="fa fa-check"></i><b>9.3.3</b> ANOVA as a Linear Model</a></li>
<li class="chapter" data-level="9.3.4" data-path="anova-part-2.html"><a href="anova-part-2.html#ancova-as-a-linear-model"><i class="fa fa-check"></i><b>9.3.4</b> ANCOVA as a Linear Model</a></li>
<li class="chapter" data-level="9.3.5" data-path="anova-part-2.html"><a href="anova-part-2.html#centering-our-covariate"><i class="fa fa-check"></i><b>9.3.5</b> Centering our Covariate</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="technical-details-and-credits.html"><a href="technical-details-and-credits.html"><i class="fa fa-check"></i>Technical Details and Credits</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Advanced Data Skills, Open Science and Reproducibility 2024/25</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-visualisation" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Workshop 4</span> Data Visualisation<a href="data-visualisation.html#data-visualisation" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Being able to build clear visualisations is key to the successful communication of your data to your intended audience.</p>
<p>There are a couple of great recent books focused on data visualisation that I suggest you have a look it. They both provide great perspectives on data visualisations and are full of wonderful examples of different kinds of data visualisations, some of which you’ll learn how to build in this workshop.</p>
<p>If you click on the image of the Claus Wilke book, you’ll be taken to the online version of the book (written in R, obviously!)</p>
<p>  </p>
<center>
<p><a href="https://socviz.co"><img src="images/healey.jpg" style="width:30.0%" alt="Link to Healey book" /></a> <a href="https://serialmentor.com/dataviz/"><img src="images/wilke.png" style="width:30.0%" alt="Link to Healey book" /></a></p>
</center>
<p>  </p>
<p>First I’d like you to watch this brief video where I give some examples of the kinds of data visualisations you can build in R, and why you probably want to avoid building bar graphs.</p>
<center>
<p>  </p>
<iframe width="560" height="315" src="https://youtube.com/embed/knMWVL8A5kw" frameborder="0" data-external="1" allowfullscreen>
</iframe>
<p>  </p>
</center>
<p>  </p>
<div id="the-basics-of-ggplot2" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> The Basics of ggplot2<a href="data-visualisation.html#the-basics-of-ggplot2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>First we need to load the ggplot2 package. As it is part of the Tidyverse (and we’re likely to be using other Tidyverse packages alongside ggplot2), we load it into our library using the <code>library(tidyverse)</code> line of code.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="data-visualisation.html#cb82-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div>
<p>In the video, I mention that using ggplot2 requires us to specify some core information in order to build our visualisations. These include the raw data that you want to plot, geometries (or geoms) that are the geometric shapes that will represent the data, and the aesthetics of the geometric and objects, such as color, size, shape and position.</p>
</div>
<div id="your-first-visualisation" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Your First Visualisation<a href="data-visualisation.html#your-first-visualisation" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Below is an example where we’re using the <code>mpg</code> dataset (which is a dataset that contains information about cars) to build a visualisation that plots the points corresponding to city fuel economy (<code>cty</code>) on the y-axis and <code>manufacturer</code> on the x-axis.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="data-visualisation.html#cb83-1" tabindex="-1"></a>mpg <span class="sc">%&gt;%</span></span>
<span id="cb83-2"><a href="data-visualisation.html#cb83-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> manufacturer, <span class="at">y =</span> cty)) <span class="sc">+</span> </span>
<span id="cb83-3"><a href="data-visualisation.html#cb83-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<p>So, this is not great. The x-axis labels are hard to read, and the individual points don’t look that pleasing. We can use the <code>str_to_title()</code> function to change the manufacturer labels to title case, and adjust the axis labels easily using the <code>theme()</code> function. Note, the <code>+</code> symbol between the lines of <code>ggplot()</code> code is equivalent to the <code>%&gt;%</code> operator. For historical reasons (basically, because <code>ggplot()</code> came before the other packages in the Tidyverse), you need to use the <code>+</code> when adding layers to your <code>ggplot()</code> visualisations.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="data-visualisation.html#cb84-1" tabindex="-1"></a>mpg <span class="sc">%&gt;%</span></span>
<span id="cb84-2"><a href="data-visualisation.html#cb84-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">manufacturer =</span> <span class="fu">str_to_title</span>(manufacturer)) <span class="sc">%&gt;%</span></span>
<span id="cb84-3"><a href="data-visualisation.html#cb84-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> manufacturer, <span class="at">y =</span> cty)) <span class="sc">+</span> </span>
<span id="cb84-4"><a href="data-visualisation.html#cb84-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb84-5"><a href="data-visualisation.html#cb84-5" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust =</span> .<span class="dv">5</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<div id="improving-the-plot" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Improving the Plot<a href="data-visualisation.html#improving-the-plot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>So let’s do some more tidying - we’re going to jitter the points slightly (so they’re not stacked vertically) using the <code>geom_jitter()</code> function, and tidy up the axis titles using the <code>labs()</code> function to explicitly add axis labels (rather than just use the labels in our dataset). We’re also adding a few other tweaks - can you spot them?</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="data-visualisation.html#cb85-1" tabindex="-1"></a>mpg <span class="sc">%&gt;%</span></span>
<span id="cb85-2"><a href="data-visualisation.html#cb85-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">manufacturer =</span> <span class="fu">str_to_title</span>(manufacturer)) <span class="sc">%&gt;%</span></span>
<span id="cb85-3"><a href="data-visualisation.html#cb85-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> manufacturer, <span class="at">y =</span> cty)) <span class="sc">+</span> </span>
<span id="cb85-4"><a href="data-visualisation.html#cb85-4" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> .<span class="dv">2</span>, <span class="at">alpha =</span> .<span class="dv">75</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb85-5"><a href="data-visualisation.html#cb85-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb85-6"><a href="data-visualisation.html#cb85-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust =</span> .<span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb85-7"><a href="data-visualisation.html#cb85-7" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>)) <span class="sc">+</span></span>
<span id="cb85-8"><a href="data-visualisation.html#cb85-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;City Fuel Economy by Car Manufacturer&quot;</span>,</span>
<span id="cb85-9"><a href="data-visualisation.html#cb85-9" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Manufacturer&quot;</span>, </span>
<span id="cb85-10"><a href="data-visualisation.html#cb85-10" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;City Fuel Economy (mpg)&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-51-1.png" width="672" /></p>
<p>It might be helpful for us to add summary statistical information such as the mean fuel economy and confidence intervals around the mean for each car manufacturer.</p>
</div>
<div id="adding-summary-statistics" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Adding Summary Statistics<a href="data-visualisation.html#adding-summary-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We need to add the <code>Hmisc</code> package to allow us to use the <code>stat_summary()</code> function.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="data-visualisation.html#cb86-1" tabindex="-1"></a><span class="fu">library</span>(Hmisc)</span></code></pre></div>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="data-visualisation.html#cb87-1" tabindex="-1"></a>mpg <span class="sc">%&gt;%</span></span>
<span id="cb87-2"><a href="data-visualisation.html#cb87-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">manufacturer =</span> <span class="fu">str_to_title</span>(manufacturer)) <span class="sc">%&gt;%</span></span>
<span id="cb87-3"><a href="data-visualisation.html#cb87-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> manufacturer, <span class="at">y =</span> cty)) <span class="sc">+</span> </span>
<span id="cb87-4"><a href="data-visualisation.html#cb87-4" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb87-5"><a href="data-visualisation.html#cb87-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb87-6"><a href="data-visualisation.html#cb87-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust =</span> .<span class="dv">5</span>)) <span class="sc">+</span></span>
<span id="cb87-7"><a href="data-visualisation.html#cb87-7" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>)) <span class="sc">+</span></span>
<span id="cb87-8"><a href="data-visualisation.html#cb87-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;City Fuel Economy by Car Manufacturer&quot;</span>,</span>
<span id="cb87-9"><a href="data-visualisation.html#cb87-9" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Manufacturer&quot;</span>, </span>
<span id="cb87-10"><a href="data-visualisation.html#cb87-10" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;City Fuel Economy (mpg)&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-53-1.png" width="672" /></p>
</div>
<div id="the-finished-plot" class="section level3 hasAnchor" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> The Finished(?) Plot<a href="data-visualisation.html#the-finished-plot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>At the moment, the x-axis is ordered alphabetically. How about we order it so that it goes from manufacturer with the hightest mean fuel economy, to the lowest. Also, how about we flip the visualisation so that the axes swap and add a few other tweaks?</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="data-visualisation.html#cb88-1" tabindex="-1"></a>mpg <span class="sc">%&gt;%</span></span>
<span id="cb88-2"><a href="data-visualisation.html#cb88-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">manufacturer =</span> <span class="fu">str_to_title</span>(manufacturer)) <span class="sc">%&gt;%</span></span>
<span id="cb88-3"><a href="data-visualisation.html#cb88-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_reorder</span>(manufacturer, <span class="at">.fun =</span> mean, cty), <span class="at">y =</span> cty, <span class="at">colour =</span> manufacturer)) <span class="sc">+</span></span>
<span id="cb88-4"><a href="data-visualisation.html#cb88-4" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb88-5"><a href="data-visualisation.html#cb88-5" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> .<span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb88-6"><a href="data-visualisation.html#cb88-6" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb88-7"><a href="data-visualisation.html#cb88-7" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>)) <span class="sc">+</span></span>
<span id="cb88-8"><a href="data-visualisation.html#cb88-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Manufacturer by City Fuel Economy&quot;</span>,</span>
<span id="cb88-9"><a href="data-visualisation.html#cb88-9" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Manufacturer&quot;</span>, </span>
<span id="cb88-10"><a href="data-visualisation.html#cb88-10" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;City Fuel Economy (mpg)&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-11"><a href="data-visualisation.html#cb88-11" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">colour =</span> <span class="st">&#39;none&#39;</span>) <span class="sc">+</span></span>
<span id="cb88-12"><a href="data-visualisation.html#cb88-12" tabindex="-1"></a>  <span class="fu">coord_flip</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-54-1.png" width="672" /></p>
<p>This looks pretty good. Can you tell what the other bits of code do that I added? Have a go changing some of the numbers to see what happens. You can prevent a line of code being run by adding a <code>#</code> in front of it. So if you need to temporarily not run a line, just add a <code>#</code> rather than delete the line.</p>
<p>Plots are rarely completely “finished” as you’ll often think of a minor aesthetic tweak that might make some improvement.</p>
</div>
<div id="using-facet_wrap" class="section level3 hasAnchor" number="4.2.4">
<h3><span class="header-section-number">4.2.4</span> Using <code>facet_wrap()</code><a href="data-visualisation.html#using-facet_wrap" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We might think that fuel economy varies as a function of the type of vehicle (e.g., sports cars may be more fuel hungry than midsize cars) and by the number size of engine (e.g., cars with bigger engines may be more fuel hungry). In the visualisation below we’re going to use the <code>facet_wrap()</code> function to build a separate visualisation for each level of the factor we are facetting over (ignoring SUVs).</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="data-visualisation.html#cb89-1" tabindex="-1"></a>mpg <span class="sc">%&gt;%</span></span>
<span id="cb89-2"><a href="data-visualisation.html#cb89-2" tabindex="-1"></a>  <span class="fu">filter</span>(class <span class="sc">!=</span> <span class="st">&quot;suv&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb89-3"><a href="data-visualisation.html#cb89-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">class =</span> <span class="fu">str_to_title</span>(class)) <span class="sc">%&gt;%</span></span>
<span id="cb89-4"><a href="data-visualisation.html#cb89-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> displ, <span class="at">y =</span> cty, <span class="at">colour =</span> class)) <span class="sc">+</span> </span>
<span id="cb89-5"><a href="data-visualisation.html#cb89-5" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb89-6"><a href="data-visualisation.html#cb89-6" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb89-7"><a href="data-visualisation.html#cb89-7" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>)) <span class="sc">+</span></span>
<span id="cb89-8"><a href="data-visualisation.html#cb89-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;City Fuel Economy by Engine Displacement&quot;</span>,</span>
<span id="cb89-9"><a href="data-visualisation.html#cb89-9" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Engine Displacement (litres)&quot;</span>, </span>
<span id="cb89-10"><a href="data-visualisation.html#cb89-10" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;City Fuel Economy (mpg)&quot;</span>) <span class="sc">+</span></span>
<span id="cb89-11"><a href="data-visualisation.html#cb89-11" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">colour =</span> <span class="st">&#39;none&#39;</span>) <span class="sc">+</span></span>
<span id="cb89-12"><a href="data-visualisation.html#cb89-12" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> class)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-55-1.png" width="672" /></p>
<p>Can you tell what each bit of code is doing? Again, edit the numbers and put a <code>#</code> before lines you want to temporarily ignore to see what happens.</p>
</div>
</div>
<div id="scatterplots" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Scatterplots<a href="data-visualisation.html#scatterplots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Above we focused on plotting a numerical variable on one axis, and a categorical variable on the other. There will be cases where we want to create scatterplots, allowing us to plot two numerical variables against each other - possibly to determine whether there might be a relationship between the two. Below we are plotting Engine Displacement on the y-axis, and City Fuel Economy on the x-axis.</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="data-visualisation.html#cb90-1" tabindex="-1"></a>mpg <span class="sc">%&gt;%</span></span>
<span id="cb90-2"><a href="data-visualisation.html#cb90-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">class =</span> <span class="fu">str_to_upper</span>(class)) <span class="sc">%&gt;%</span></span>
<span id="cb90-3"><a href="data-visualisation.html#cb90-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> cty, <span class="at">y =</span> displ)) <span class="sc">+</span></span>
<span id="cb90-4"><a href="data-visualisation.html#cb90-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">colour =</span> class)) <span class="sc">+</span></span>
<span id="cb90-5"><a href="data-visualisation.html#cb90-5" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb90-6"><a href="data-visualisation.html#cb90-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>)) <span class="sc">+</span></span>
<span id="cb90-7"><a href="data-visualisation.html#cb90-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span> </span>
<span id="cb90-8"><a href="data-visualisation.html#cb90-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;City Fuel Economy (mpg)&quot;</span>,</span>
<span id="cb90-9"><a href="data-visualisation.html#cb90-9" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Engine Displacement (litres)&quot;</span>, </span>
<span id="cb90-10"><a href="data-visualisation.html#cb90-10" tabindex="-1"></a>       <span class="at">colour =</span> <span class="st">&quot;Vehicle Class&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-56-1.png" width="672" /></p>
<p>In the above example, we used the <code>geom_smooth()</code> function to add a layer corresponding to fitting a curve to our data. We can see a fairly clear negative correlation between Engine Displacement and Fuel Economy for Fuel Economy values that are less than 25 mpg, but little relationship between the two for values that are great than 25 mpg. These seems to suggest there are some cars with relatively small engines that have great fuel economy, and others with similar engine sizes that have much worse fuel economy.</p>
</div>
<div id="plotting-histograms" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Plotting Histograms<a href="data-visualisation.html#plotting-histograms" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We might want to plot a histogram of engine sizes (measured in litres and captured in the variable <code>displ</code> in the <code>mpg</code> dataset) to get a feel for how this variable is distributed.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="data-visualisation.html#cb91-1" tabindex="-1"></a>mpg <span class="sc">%&gt;%</span></span>
<span id="cb91-2"><a href="data-visualisation.html#cb91-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> displ)) <span class="sc">+</span></span>
<span id="cb91-3"><a href="data-visualisation.html#cb91-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> .<span class="dv">5</span>, <span class="at">fill =</span> <span class="st">&quot;grey&quot;</span>) <span class="sc">+</span></span>
<span id="cb91-4"><a href="data-visualisation.html#cb91-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Histogram of Engine Displacement&quot;</span>,</span>
<span id="cb91-5"><a href="data-visualisation.html#cb91-5" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Engine Displacement (litres)&quot;</span>,</span>
<span id="cb91-6"><a href="data-visualisation.html#cb91-6" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Count&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<div id="the-ggridges-package" class="section level3 hasAnchor" number="4.4.1">
<h3><span class="header-section-number">4.4.1</span> The <code>ggridges</code> Package<a href="data-visualisation.html#the-ggridges-package" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Given in a previous visualisation we saw that there seemed to be variability between vehicle classes, wouldn’t it be great if we could compare the distributions of engine size separated by vehicle class? We’re now going to use the <code>ggridges</code> package to do just that…</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="data-visualisation.html#cb92-1" tabindex="-1"></a><span class="fu">library</span>(ggridges)</span></code></pre></div>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="data-visualisation.html#cb93-1" tabindex="-1"></a>mpg <span class="sc">%&gt;%</span></span>
<span id="cb93-2"><a href="data-visualisation.html#cb93-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">class =</span> <span class="fu">str_to_title</span>(class)) <span class="sc">%&gt;%</span></span>
<span id="cb93-3"><a href="data-visualisation.html#cb93-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> displ, <span class="at">y =</span> <span class="fu">fct_reorder</span>(class, <span class="at">.fun =</span> mean, displ))) <span class="sc">+</span></span>
<span id="cb93-4"><a href="data-visualisation.html#cb93-4" tabindex="-1"></a>  <span class="fu">geom_density_ridges</span>(<span class="at">height =</span> .<span class="dv">5</span>, <span class="fu">aes</span>(<span class="at">fill =</span> class)) <span class="sc">+</span></span>
<span id="cb93-5"><a href="data-visualisation.html#cb93-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb93-6"><a href="data-visualisation.html#cb93-6" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>)) <span class="sc">+</span></span>
<span id="cb93-7"><a href="data-visualisation.html#cb93-7" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">&#39;none&#39;</span>) <span class="sc">+</span> </span>
<span id="cb93-8"><a href="data-visualisation.html#cb93-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Engine Displacement (litres)&quot;</span>,</span>
<span id="cb93-9"><a href="data-visualisation.html#cb93-9" tabindex="-1"></a>       <span class="at">y =</span> <span class="cn">NULL</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-59-1.png" width="672" /></p>
<p>We can see from the above visualisation that SUVs seem to have quite a lot of variability in engine size while compact cars have relatively little variability.</p>
</div>
</div>
<div id="the-nhanes-dataset" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> The NHANES Dataset<a href="data-visualisation.html#the-nhanes-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We’re now going to visualise aspects of the NHANES dataset.</p>
<p>  </p>
<blockquote>
<p>This is survey data collected by the US National Center for Health Statistics (NCHS) which has conducted a series of health and nutrition surveys since the early 1960’s. Since 1999 approximately 5,000 individuals of all ages are interviewed in their homes every year and complete the health examination component of the survey. The health examination is conducted in a mobile examination centre (MEC). The NHANES target population is “the non-institutionalized civilian resident population of the United States”. NHANES, (American National Health and Nutrition Examination surveys), use complex survey designs (see <a href="http://www.cdc.gov/nchs/data/series/sr_02/sr02_162.pdf" class="uri">http://www.cdc.gov/nchs/data/series/sr_02/sr02_162.pdf</a>) that oversample certain subpopulations like racial minorities. Naive analysis of the original NHANES data can lead to mistaken conclusions. The percentages of people from each racial group in the data, for example, are quite different from the way they are in the population.</p>
</blockquote>
<p>  </p>
<p>We need to load the <code>NHANES</code> package as this is where the dataset is contained.</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="data-visualisation.html#cb94-1" tabindex="-1"></a><span class="fu">library</span>(NHANES)</span></code></pre></div>
<p>If running the above command generated an error, is it because you haven’t installed the package on your machine with <code>install.packages("NHANES")</code>?</p>
<p>First we’re going to explore the NHANES dataset.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="data-visualisation.html#cb95-1" tabindex="-1"></a><span class="fu">ncol</span>(NHANES)</span></code></pre></div>
<pre><code>## [1] 76</code></pre>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="data-visualisation.html#cb97-1" tabindex="-1"></a><span class="fu">nrow</span>(NHANES)</span></code></pre></div>
<pre><code>## [1] 10000</code></pre>
<p>We see there are 76 columns and 10,000 rows. If we use the function <code>head()</code> we can see the first few rows of the dataframe.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="data-visualisation.html#cb99-1" tabindex="-1"></a><span class="fu">head</span>(NHANES)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 76
##      ID SurveyYr Gender   Age AgeDecade AgeMonths Race1 Race3 Education   
##   &lt;int&gt; &lt;fct&gt;    &lt;fct&gt;  &lt;int&gt; &lt;fct&gt;         &lt;int&gt; &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;       
## 1 51624 2009_10  male      34 &quot; 30-39&quot;        409 White &lt;NA&gt;  High School 
## 2 51624 2009_10  male      34 &quot; 30-39&quot;        409 White &lt;NA&gt;  High School 
## 3 51624 2009_10  male      34 &quot; 30-39&quot;        409 White &lt;NA&gt;  High School 
## 4 51625 2009_10  male       4 &quot; 0-9&quot;           49 Other &lt;NA&gt;  &lt;NA&gt;        
## 5 51630 2009_10  female    49 &quot; 40-49&quot;        596 White &lt;NA&gt;  Some College
## 6 51638 2009_10  male       9 &quot; 0-9&quot;          115 White &lt;NA&gt;  &lt;NA&gt;        
## # ℹ 67 more variables: MaritalStatus &lt;fct&gt;, HHIncome &lt;fct&gt;, HHIncomeMid &lt;int&gt;,
## #   Poverty &lt;dbl&gt;, HomeRooms &lt;int&gt;, HomeOwn &lt;fct&gt;, Work &lt;fct&gt;, Weight &lt;dbl&gt;,
## #   Length &lt;dbl&gt;, HeadCirc &lt;dbl&gt;, Height &lt;dbl&gt;, BMI &lt;dbl&gt;,
## #   BMICatUnder20yrs &lt;fct&gt;, BMI_WHO &lt;fct&gt;, Pulse &lt;int&gt;, BPSysAve &lt;int&gt;,
## #   BPDiaAve &lt;int&gt;, BPSys1 &lt;int&gt;, BPDia1 &lt;int&gt;, BPSys2 &lt;int&gt;, BPDia2 &lt;int&gt;,
## #   BPSys3 &lt;int&gt;, BPDia3 &lt;int&gt;, Testosterone &lt;dbl&gt;, DirectChol &lt;dbl&gt;,
## #   TotChol &lt;dbl&gt;, UrineVol1 &lt;int&gt;, UrineFlow1 &lt;dbl&gt;, UrineVol2 &lt;int&gt;, …</code></pre>
<div id="tidying-the-data" class="section level3 hasAnchor" number="4.5.1">
<h3><span class="header-section-number">4.5.1</span> Tidying the Data<a href="data-visualisation.html#tidying-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>It looks like some participants appear more than once in the dataset - this could be due to the oversampling mentioned in the description - the first few rows are all for participant ID 51624. We can use the <code>select()</code> function alongwith the <code>n_distinct()</code> function to tell us the unique number of IDs in the dataset.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="data-visualisation.html#cb101-1" tabindex="-1"></a>NHANES <span class="sc">%&gt;%</span> </span>
<span id="cb101-2"><a href="data-visualisation.html#cb101-2" tabindex="-1"></a>  <span class="fu">select</span>(ID) <span class="sc">%&gt;%</span> </span>
<span id="cb101-3"><a href="data-visualisation.html#cb101-3" tabindex="-1"></a>  <span class="fu">n_distinct</span>()</span></code></pre></div>
<pre><code>## [1] 6779</code></pre>
<p>We see we have 6,779 unique individuals. Let’s tidy our data to remove duplicate IDs. Note that below we’re using the pipe operator <code>%&gt;%</code> You can read it as ‘and then’ so it means we’re taking the NHANES dataset and then filtering it keeping just rows with distinct ID numbers. The pipe operator really helps with the readability of your data wrangling code and is an integral part of the tidyverse philosophy - tidy data and tidy code.</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="data-visualisation.html#cb103-1" tabindex="-1"></a>NHANES_tidied <span class="ot">&lt;-</span> NHANES <span class="sc">%&gt;%</span> </span>
<span id="cb103-2"><a href="data-visualisation.html#cb103-2" tabindex="-1"></a>  <span class="fu">distinct</span>(ID, <span class="at">.keep_all =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="data-visualisation.html#cb104-1" tabindex="-1"></a><span class="fu">ncol</span>(NHANES_tidied)</span></code></pre></div>
<pre><code>## [1] 76</code></pre>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="data-visualisation.html#cb106-1" tabindex="-1"></a><span class="fu">nrow</span>(NHANES_tidied)</span></code></pre></div>
<pre><code>## [1] 6779</code></pre>
<p>OK, so our tidied dataset is assigned to the variable NHANES_tidied and has 6,779 rows (but still 76 columns) - as we’d expect given we have 6,779 unique individuals.</p>
</div>
<div id="plotting-a-histogram" class="section level3 hasAnchor" number="4.5.2">
<h3><span class="header-section-number">4.5.2</span> Plotting a Histogram<a href="data-visualisation.html#plotting-a-histogram" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s start exploring the data. We have lots of potential variables and relationships to explore. I see we have one labelled <code>Education</code> which is coded as a factor. We also have information related to health such as BMI - first of all lets plot a histogram of BMI.</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="data-visualisation.html#cb108-1" tabindex="-1"></a>NHANES_tidied <span class="sc">%&gt;%</span></span>
<span id="cb108-2"><a href="data-visualisation.html#cb108-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> BMI)) <span class="sc">+</span> </span>
<span id="cb108-3"><a href="data-visualisation.html#cb108-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">100</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<p>We see a pretty right skewed distribution here. Note our use of the <code>na.rm</code> parameter - this parameter appears in many tidyverse functions and by setting it to TRUE we tell R to ignore any parts of our data frame where we have missing data (which is indicated by <code>NA</code>).</p>
</div>
<div id="summary-statistics" class="section level3 hasAnchor" number="4.5.3">
<h3><span class="header-section-number">4.5.3</span> Summary Statistics<a href="data-visualisation.html#summary-statistics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Does BMI vary as a function of Education level? In the code below we are using the data stored in the variable <code>NHANES_tidied</code>, grouping it by Education, then summarising to generate the median BMI for each of our groups. Again, we use the <code>na.rm = TRUE</code> parameter with the <code>summarise()</code> function this time to remove any missing values (<code>NA</code>) from our calculation.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="data-visualisation.html#cb109-1" tabindex="-1"></a>NHANES_tidied <span class="sc">%&gt;%</span> </span>
<span id="cb109-2"><a href="data-visualisation.html#cb109-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Education) <span class="sc">%&gt;%</span> </span>
<span id="cb109-3"><a href="data-visualisation.html#cb109-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">median =</span> <span class="fu">median</span>(BMI, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 6 × 2
##   Education      median
##   &lt;fct&gt;           &lt;dbl&gt;
## 1 8th Grade        28.6
## 2 9 - 11th Grade   28.2
## 3 High School      28.2
## 4 Some College     28.4
## 5 College Grad     26.5
## 6 &lt;NA&gt;             18.9</code></pre>
<p>So it looks like those with College eduction have the lowest median BMI (ignoring the <code>NA</code> category which corresponds to cases where we don’t have Education level recorded).</p>
</div>
<div id="geom_violin" class="section level3 hasAnchor" number="4.5.4">
<h3><span class="header-section-number">4.5.4</span> <code>geom_violin()</code><a href="data-visualisation.html#geom_violin" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s graph it! Note here we’re filtering out cases where we don’t have BMI value recorded. The function <code>is.na()</code> returns TRUE when applied to a case of missing data (<code>NA</code>) - we use the <code>!</code> operator to negate this and combine several of these expressions together using the logical AND operator <code>&amp;</code>.</p>
<p>The line of code below starting with <code>filter()</code> means filter cases where Education is not missing AND BMI is not missing. This means that the <code>NHANES_tidied</code> data that gets passed to the <code>ggplot()</code> call has no missing data for the key variables we’re interested in.</p>
<p>I then add a <code>geom_violin()</code> layer to capture the shape of the distribution for each level of Education and <code>geom_boxplot()</code> layer to create a boxplot for each level of our Education factor.</p>
<p>The <code>guides(colour = 'none')</code> call suppresses displaying the colour legend - place a <code>#</code> in front of it and rerun the code to see what changes.</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="data-visualisation.html#cb111-1" tabindex="-1"></a>NHANES_tidied <span class="sc">%&gt;%</span> </span>
<span id="cb111-2"><a href="data-visualisation.html#cb111-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Education) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(BMI)) <span class="sc">%&gt;%</span></span>
<span id="cb111-3"><a href="data-visualisation.html#cb111-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Education, <span class="at">y =</span> BMI, <span class="at">colour =</span> Education)) <span class="sc">+</span> </span>
<span id="cb111-4"><a href="data-visualisation.html#cb111-4" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb111-5"><a href="data-visualisation.html#cb111-5" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> .<span class="dv">2</span>, <span class="at">width =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb111-6"><a href="data-visualisation.html#cb111-6" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb111-7"><a href="data-visualisation.html#cb111-7" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">colour =</span> <span class="st">&#39;none&#39;</span>) <span class="sc">+</span> </span>
<span id="cb111-8"><a href="data-visualisation.html#cb111-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Examining the effect of education level on BMI&quot;</span>, </span>
<span id="cb111-9"><a href="data-visualisation.html#cb111-9" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Education Level&quot;</span>, </span>
<span id="cb111-10"><a href="data-visualisation.html#cb111-10" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;BMI&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-68-1.png" width="672" /></p>
</div>
<div id="plotting-interaction-effects" class="section level3 hasAnchor" number="4.5.5">
<h3><span class="header-section-number">4.5.5</span> Plotting Interaction Effects<a href="data-visualisation.html#plotting-interaction-effects" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can also plot how two factors interact with each other. For the plot above, we’ll now add the factor <code>Diabetes</code> (which has two levels - Yes vs. No) to see how that might interact with Education level. To capture the nature of this interaction, we use the expression <code>Education:Diabetes</code> when we specify the x-axis aesthetic. Note, I have rotated the x-axis labels 45 degrees to make them easier to read.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="data-visualisation.html#cb112-1" tabindex="-1"></a>NHANES_tidied <span class="sc">%&gt;%</span> </span>
<span id="cb112-2"><a href="data-visualisation.html#cb112-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Education) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(BMI) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(Diabetes)) <span class="sc">%&gt;%</span></span>
<span id="cb112-3"><a href="data-visualisation.html#cb112-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Education<span class="sc">:</span>Diabetes, <span class="at">y =</span> BMI, <span class="at">colour =</span> Education)) <span class="sc">+</span> </span>
<span id="cb112-4"><a href="data-visualisation.html#cb112-4" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb112-5"><a href="data-visualisation.html#cb112-5" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> .<span class="dv">2</span>, <span class="at">width =</span> .<span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb112-6"><a href="data-visualisation.html#cb112-6" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> .<span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb112-7"><a href="data-visualisation.html#cb112-7" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">colour =</span> <span class="st">&#39;none&#39;</span>) <span class="sc">+</span> </span>
<span id="cb112-8"><a href="data-visualisation.html#cb112-8" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span></span>
<span id="cb112-9"><a href="data-visualisation.html#cb112-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Examining the effect of education level and diabetes on BMI&quot;</span>, </span>
<span id="cb112-10"><a href="data-visualisation.html#cb112-10" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Education Level x Diabetes&quot;</span>, </span>
<span id="cb112-11"><a href="data-visualisation.html#cb112-11" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;BMI&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p>We can see from the above plot that those with Diabetes seem to also have higher BMI scores for each level of Education.</p>
</div>
<div id="histograms-with-facet_wrap" class="section level3 hasAnchor" number="4.5.6">
<h3><span class="header-section-number">4.5.6</span> Histograms with <code>facet_wrap()</code><a href="data-visualisation.html#histograms-with-facet_wrap" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can also plot histograms of BMI separately for each Education level - we use the <code>facet_wrap()</code> function to do this.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="data-visualisation.html#cb113-1" tabindex="-1"></a>NHANES_tidied <span class="sc">%&gt;%</span> </span>
<span id="cb113-2"><a href="data-visualisation.html#cb113-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Education) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(BMI)) <span class="sc">%&gt;%</span></span>
<span id="cb113-3"><a href="data-visualisation.html#cb113-3" tabindex="-1"></a>  <span class="fu">group_by</span>(Education) <span class="sc">%&gt;%</span> </span>
<span id="cb113-4"><a href="data-visualisation.html#cb113-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> BMI, <span class="at">fill =</span> Education)) <span class="sc">+</span></span>
<span id="cb113-5"><a href="data-visualisation.html#cb113-5" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb113-6"><a href="data-visualisation.html#cb113-6" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">&#39;none&#39;</span>) <span class="sc">+</span> </span>
<span id="cb113-7"><a href="data-visualisation.html#cb113-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Examining the effect of education level on BMI&quot;</span>,</span>
<span id="cb113-8"><a href="data-visualisation.html#cb113-8" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;BMI&quot;</span>, </span>
<span id="cb113-9"><a href="data-visualisation.html#cb113-9" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Number of cases&quot;</span>) <span class="sc">+</span> </span>
<span id="cb113-10"><a href="data-visualisation.html#cb113-10" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Education)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>
<p>In the above graph, notice that the same y-axis scale is used for each plot - this makes comparisons a little tricky as there are different numbers of cases for each Eduction level. Add the following <code>scales = "free"</code> after <code>Education</code> in the <code>facet_wrap()</code> line. What changes?</p>
<p>Instead of generating the histograms using a count, we could generate them using a density function. Let’s also add a density curve.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="data-visualisation.html#cb114-1" tabindex="-1"></a>NHANES_tidied <span class="sc">%&gt;%</span> </span>
<span id="cb114-2"><a href="data-visualisation.html#cb114-2" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Education) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(BMI)) <span class="sc">%&gt;%</span></span>
<span id="cb114-3"><a href="data-visualisation.html#cb114-3" tabindex="-1"></a>  <span class="fu">group_by</span>(Education) <span class="sc">%&gt;%</span> </span>
<span id="cb114-4"><a href="data-visualisation.html#cb114-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> BMI, <span class="at">fill =</span> Education)) <span class="sc">+</span></span>
<span id="cb114-5"><a href="data-visualisation.html#cb114-5" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..)) <span class="sc">+</span></span>
<span id="cb114-6"><a href="data-visualisation.html#cb114-6" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">y =</span> ..density..)) <span class="sc">+</span></span>
<span id="cb114-7"><a href="data-visualisation.html#cb114-7" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">fill =</span> <span class="st">&#39;none&#39;</span>) <span class="sc">+</span> </span>
<span id="cb114-8"><a href="data-visualisation.html#cb114-8" tabindex="-1"></a>  <span class="fu">labs</span>( <span class="at">title =</span> <span class="st">&quot;Examining the effect of education level on BMI&quot;</span>, </span>
<span id="cb114-9"><a href="data-visualisation.html#cb114-9" tabindex="-1"></a>        <span class="at">x =</span> <span class="st">&quot;BMI&quot;</span>, </span>
<span id="cb114-10"><a href="data-visualisation.html#cb114-10" tabindex="-1"></a>        <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>) <span class="sc">+</span> </span>
<span id="cb114-11"><a href="data-visualisation.html#cb114-11" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Education)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-71-1.png" width="672" /></p>
</div>
</div>
<div id="your-challenge-do-this-during-the-in-person-session-1" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Your Challenge (do this during the in-person session)<a href="data-visualisation.html#your-challenge-do-this-during-the-in-person-session-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Create some new visualisations with either the <code>mpg</code> or <code>NHANES</code> datasets. There are many possible visualisations you could build with either dataset.</p>
</div>
<div id="additional-resources" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> Additional Resources<a href="data-visualisation.html#additional-resources" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If you are interested in understanding more about ggplot2, you might be interested in watching these two (very) detailed webinars by Thomas Lin Pedersen, one of the developers working on ggplot2 and related packages.</p>
<center>
<p><a href="https://youtu.be/h29g21z0a68"><img src="images/ggplot2_pt1.png" style="width:75.0%" alt="Link to ggplot2 video part 1" /></a></p>
<p><a href="https://youtu.be/0m4yywqNPVY"><img src="images/ggplot2_pt2.png" style="width:75.0%" alt="Link to ggplot2 video part 2" /></a></p>
</center>
<center>
<strong>End of workshop 4 materials</strong>
</center>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-wrangling-and-data-summarising.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="r-markdown.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
